---
title: "Supplemental Figure 2"
author: IBBruns
output: html_document
date: "2025-11-26"
---


# Set up script
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
standard_plotTheme <- theme_minimal() +
  theme(
    plot.title = element_text(
      size = 15,
      face = "bold",
      vjust = 2,
      hjust = 0.5
    ),
    plot.subtitle = element_text(
      size = 13,
      face = "italic",
      vjust = 2,
      hjust = 0.5
    ),
    axis.title.x = element_text(size = 12, vjust = 0.25),
    axis.title.y = element_text(size = 12, vjust = 1),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 12)
  )


theme_set(standard_plotTheme)

# define 6 custom colors
timepoint_cols <- c(
  "#1f77b4",  # blue 
  "#d95f02",  # orange
  "#7570b3",  # violet
  "#e7298a",  # magenta/pink
  "#66a61e",  # green
  "#e6ab02"   # mustard yellow
)

```



MANUSCRIPT FIGURE 2
Here, we will generate figure 2 from the PARC ab initio manuscript

# Settings

## Set studyNR
```{r}
studyNR = "EUT046"
```


## Load packages
```{r}
pacman::p_load(tidyverse, here, ggpubr, patchwork, grid, GGally, ggplotify)
```


## Load functions
```{r}
source(here("functions.R"), local = knitr::knit_global())
```



## Directories
```{r}
inputDir = file.path(here(), "input", studyNR)
outputDir = file.path(here(), "output", studyNR)

if(!dir.exists(outputDir)){
  dir.create(outputDir)
}

plotDir = file.path(here(), "figures", studyNR)

if(!dir.exists(plotDir)){
  dir.create(plotDir)
}
```



# Load data
```{r}
load(file.path(outputDir, "WrangledInput", "WrangledInputData.RData"))

tPOD_genelevel = readxl::read_xlsx(file.path(inputDir, "tPOD_calculations_geneLevel_alltp.xlsx")) %>%
  mutate(time_num = as.numeric(gsub("h", "", timepoint)),
         timepoint = factor(timepoint, levels = c("4h", "8h", "16h", "24h", "48h", "72h"))) %>% pivot_longer(
           cols = c("AristotleU", "BPI", "GhentU", "LeidenU", "Sciensano"),
           names_to = "partner",
           values_to = "tPOD"
         )

```


# Generate figure

## Line plot
```{r}
ggplot(tPOD_genelevel, aes(x = timepoint, y = tPOD, color = partner, group = partner)) +
  geom_point(size = 3) +
  geom_line() +
  facet_wrap(~ tPOD_measure, nrow = 1) +
  labs(
    x = "",
    y = "tPOD",
    color = "",
    title = "Comparison of tPOD Estimates Across Partners over Time"
  ) +
  theme_bw() +
  theme(
    strip.text = element_text(size = 12, face = "bold"),
    strip.background = element_rect(fill = "white", colour = "black"),
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 11),
    legend.text = element_text(size = 12)
  ) +
  scale_color_manual(values = c("firebrick","gray30", "gold1", "blue2", "forestgreen"))

ggsave(file.path(plotDir, "SupplementalFigure2.pdf"), width = 10, height = 5)

```



