---
title: "SupplementalFigure2_new"
output: html_document
date: "2025-12-15"
---

# Set up script
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
standard_plotTheme <- theme_minimal() +
  theme(
    plot.title = element_text(
      size = 15,
      face = "bold",
      vjust = 2,
      hjust = 0.5
    ),
    plot.subtitle = element_text(
      size = 13,
      face = "italic",
      vjust = 2,
      hjust = 0.5
    ),
    axis.title.x = element_text(size = 12, vjust = 0.25),
    axis.title.y = element_text(size = 12, vjust = 1),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 12)
  )


theme_set(standard_plotTheme)

# define 6 custom colors
timepoint_cols <- c(
  "#1f77b4",  # blue 
  "#d95f02",  # orange
  "#7570b3",  # violet
  "#e7298a",  # magenta/pink
  "#66a61e",  # green
  "#e6ab02"   # mustard yellow
)

```



MANUSCRIPT FIGURE 2
Here, we will generate figure 2 from the PARC ab initio manuscript

# Settings

## Set studyNR
```{r}
studyNR = "EUT046"
```


## Load packages
```{r}
pacman::p_load(tidyverse, here, patchwork, data.table)
```


## Load functions
```{r}
source(here("functions.R"), local = knitr::knit_global())
```



## Directories
```{r}
inputDir = file.path(here(), "input", studyNR)
outputDir = file.path(here(), "output", studyNR)

if(!dir.exists(outputDir)){
  dir.create(outputDir)
}

plotDir = file.path(here(), "figures", studyNR)

if(!dir.exists(plotDir)){
  dir.create(plotDir)
}
```



# Load data
```{r}
load(file.path(outputDir, "WrangledInput", "WrangledInputData.RData"))

LU_norm_BMD = fread(file.path(inputDir, "Leiden", paste0(studyNR, "_log2cpm_BMD_output.txt")), check.names = TRUE) %>%
  filter(Best.BMD >= 0.1*0.1 & Best.BMD <= 50,
         Best.BMD.BMDL < 20,
         Best.BMDU.BMD < 20,
         Best.RSquared >= 0.8) %>% # for Leiden filter needs te be applied; this is the direct output from BMDExpress
  mutate(timepoint = factor(
  str_extract(Analysis, "\\d{1,2}h"), 
  levels = c("4h", "8h", "16h", "24h", "48h", "72h")
  ))


Sciensano_norm_BMD = fread(file.path(inputDir, "Sciensano", "BMD_output_normalized_counts.txt"), check.names = TRUE) %>%
  filter(Best.BMD <= 50,
         Best.BMD.BMDL <= 20,
         Best.BMDU.BMDL <= 40,
         Best.RSquared >= 0.8) %>% # for Sciensano filter needs te be applied; copied from OECD reporting table
  mutate(timepoint = factor(
  str_extract(Analysis, "\\d{1,2}h"), 
  levels = c("4h", "8h", "16h", "24h", "48h", "72h")
  ))



```



# Generate figure

```{r, fig.width=15, fig.height=8}
library(RColorBrewer)
model_cols <- c(
  "Exp 3"   = brewer.pal(7, "Set1")[1],
  "Exp 5"   = brewer.pal(7, "Set1")[2],
  "Hill"    = brewer.pal(7, "Set1")[3],
  "Linear"  = brewer.pal(7, "Set1")[4],
  "Poly 2"  = brewer.pal(7, "Set1")[5],
  "Poly 3"  = brewer.pal(7, "Set1")[6],
  "Power"   = brewer.pal(7, "Set1")[7]
)

# LeidenU
norm_BMD_combined_wide_LUmodels = norm_BMD_combined_wide %>%
  left_join(LU_norm_BMD %>% select("gene_symbol_entrez_id" = Probe.ID, Best.Model, timepoint), by = c("gene_symbol_entrez_id", "timepoint")) %>%
  filter(!is.na(Best.Model)) 


p1 = norm_BMD_combined_wide_LUmodels %>%
  ggplot(aes(x=LU_finalBMD, y=AU_finalBMD, color = Best.Model)) +
  geom_point(size = 0.5) +
  labs(x = "BMC (BMDE-noWTT-CPM-RF-S5)",
       y = "BMC (DRO-Quad-UQ-RF-S0)", 
       color = "Best Model") +
  scale_color_manual(values = model_cols)

p2 = norm_BMD_combined_wide_LUmodels %>%
  ggplot(aes(x=LU_finalBMD, y=BPI_finalBMD, color = Best.Model)) +
  geom_point(size = 0.5) +
  labs(x = "BMC (BMDE-noWTT-CPM-RF-S5)",
       y = "BMC (DRO-Quad-VST-C10-S0)", 
       color = "Best Model") +
  scale_color_manual(values = model_cols)

p3 = norm_BMD_combined_wide_LUmodels %>%
  ggplot(aes(x=LU_finalBMD, y=GU_finalBMD, color = Best.Model)) +
  geom_point(size = 0.5) +
  labs(x = "BMC (BMDE-noWTT-CPM-RF-S5)",
       y = "BMC (DRO-Quad-VST-RF-S0)", 
       color = "Best Model")+
  scale_color_manual(values = model_cols)

p4 = norm_BMD_combined_wide_LUmodels %>%
  ggplot(aes(x=LU_finalBMD, y=SC_finalBMD, color = Best.Model)) +
  geom_point(size = 0.5) +
  labs(x = "BMC (BMDE-noWTT-CPM-RF-S5)",
       y = "BMC (BMDE-WTT-CPM-RF-S0)", 
       color = "Best Model")+
  scale_color_manual(values = model_cols)




# Sciensano
norm_BMD_combined_wide_SCmodels = norm_BMD_combined_wide %>%
  left_join(Sciensano_norm_BMD %>% select(gene_symbol_entrez_id, Best.Model, timepoint), by = c("gene_symbol_entrez_id", "timepoint")) %>%
  filter(!is.na(Best.Model))


p5 = norm_BMD_combined_wide_SCmodels %>%
  ggplot(aes(x=SC_finalBMD, y=AU_finalBMD, color = Best.Model)) +
  geom_point(size = 0.5) +
  labs(x = "BMC (BMDE-WTT-CPM-RF-S0)",
       y = "BMC (DRO-Quad-UQ-RF-S0)", 
       color = "Best Model") +
  scale_color_manual(values = model_cols)

p6 = norm_BMD_combined_wide_SCmodels %>%
  ggplot(aes(x=SC_finalBMD, y=BPI_finalBMD, color = Best.Model)) +
  geom_point(size = 0.5) +
  labs(x = "BMC (BMDE-WTT-CPM-RF-S0)",
       y = "BMC (DRO-Quad-VST-C10-S0)", 
       color = "Best Model") +
  scale_color_manual(values = model_cols)

p7 = norm_BMD_combined_wide_SCmodels %>%
  ggplot(aes(x=SC_finalBMD, y=GU_finalBMD, color = Best.Model)) +
  geom_point(size = 0.5) +
  labs(x = "BMC (BMDE-WTT-CPM-RF-S0)",
       y = "BMC (DRO-Quad-VST-RF-S0)", 
       color = "Best Model") +
  scale_color_manual(values = model_cols)

p8 = norm_BMD_combined_wide_SCmodels %>%
  ggplot(aes(x=SC_finalBMD, y=LU_finalBMD, color = Best.Model)) +
  geom_point(size = 0.5) +
  labs(x = "BMC (BMDE-WTT-CPM-RF-S0)",
       y = "BMC (BMDE-noWTT-CPM-RF-S5)", 
       color = "Best Model") +
  scale_color_manual(values = model_cols)



# combine
row1 <-
  wrap_elements(
    p1 + p2 + p3 + p4 +
      plot_layout(nrow=1, axis = "collect", guides = "collect") +
  plot_annotation(
    title = "BMDE-noWTT-CPM-RF-S5 Models Fit",
    tag_levels = "I"
  ))

row2 <- wrap_elements(
 p5 + p6 + p7 + p8 +
   plot_layout(nrow = 1, axis = "collect", guides = "collect") +
  plot_annotation(
    title = "BMDE-WTT-CPM-RF-S0 Models Fit",
    tag_levels = "I"
  ))

SupplementalFigure3 <-
  (row1 / row2) +
  plot_layout(axis = "collect", guides = "collect")

SupplementalFigure3

ggsave(
  filename = file.path(plotDir, "SupplementalFigure3.pdf"),
  plot = SupplementalFigure3,
  width = 15,
  height = 8
)


```

