---
title: "WrangleData"
output: html_document
date: "2025-04-24"
---

# setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# wrangle data for plots
# Settings

## Manual settings
```{r}
studyNR = "EUT046"

```


## Load packages
```{r}
pacman::p_load(tidyverse, ActivePathways, here, data.table)
```


## Load functions
```{r}
source(here("functions.R"), local = knitr::knit_global())
```



## Directories
```{r}
inputDir = file.path(here(), "input", studyNR)
outputDir = file.path(here(), "output", studyNR)

if(!dir.exists(outputDir)){
  dir.create(outputDir)
}

plotDir = file.path(here(), "figures", studyNR)

if(!dir.exists(plotDir)){
  dir.create(plotDir)
}
```



# Load data
```{r}

# BMD normalized counts
AU_norm_BMD = fread(file.path(inputDir, "Aristotle", paste0(studyNR, "_log2cpm_All_BMD_output.txt")), check.names = TRUE)

GU_norm_BMD = fread(file.path(inputDir, "Ghent", "BMD_output_normalized_counts.txt"), sep = " ", check.names = TRUE) 

LU_norm_BMD = fread(file.path(inputDir, "Leiden", paste0(studyNR, "_log2cpm_BMD_output.txt")), check.names = TRUE) %>%
  filter(Best.BMD >= 0.1*0.1 & Best.BMD <= 50,
         Best.BMD.BMDL < 20,
         Best.BMDU.BMD < 20,
         Best.RSquared >= 0.8) # for Leiden filter needs te be applied; this is the direct output from BMDExpress


Sciensano_norm_BMD = fread(file.path(inputDir, "Sciensano", "BMD_output_normalized_counts.txt"), check.names = TRUE) %>%
  filter(Best.BMD <= 50,
         Best.BMD.BMDL <= 20,
         Best.BMDU.BMDL <= 40,
         Best.RSquared >= 0.8) # for Sciensano filter needs te be applied; copied from OECD reporting table

BPI_norm_BMD = fread(file.path(inputDir, "BPI" , "All_FilteredDRomicV3.txt"), check.names = TRUE) 


# BMD log2fc
LU_fc_BMD = fread(file.path(inputDir, "Leiden", paste0(studyNR, "_log2fc_BMD_output.txt")), check.names = TRUE) %>% 
  filter(Best.BMD >= 0.1*0.1 & Best.BMD <= 50,
         Best.BMD.BMDL < 20,
         Best.BMDU.BMD < 20,
         Best.RSquared >= 0.8) # for Leiden filter needs te be applied; this is the direct output from BMDExpress


ODAF_fc_BMD = fread(file.path(inputDir, "ODAF", paste0(studyNR, "_RODAF_log2fc_BMD_output.txt")), check.names = TRUE) %>%
  filter(Best.BMD >= 0.1*0.1 & Best.BMD <= 50,
         Best.BMD.BMDL < 20,
         Best.BMDU.BMD < 20,
         Best.RSquared >= 0.8) # for R-ODAF filter needs te be applied; this is the direct output from BMDExpress


# Median BMD biological entity

# AU_norm_HALLMARK = fread()
AU_norm_HALLMARK = fread(file.path(inputDir, "Aristotle", paste0(studyNR, "_HALLMARK_Pathway_Medians_BMD_output.txt")), check.names = TRUE) 

AU_norm_KEGG = fread(file.path(inputDir, "Aristotle", paste0(studyNR, "_KEGG_Pathway_Medians_BMD_output.txt")), check.names = TRUE) 

GU_norm_HALLMARK = fread(file.path(inputDir, "Ghent", "medianBMD_pathways_normalized_counts.txt"), sep = " ", check.names = TRUE)

LU_norm_HALLMARK = fread(file.path(inputDir, "Leiden", paste0(studyNR, "_log2cpm_functionalClas_HALLMARK_output.txt")), check.names = TRUE) %>%
  filter(Genes.That.Passed.All.Filters >= 3 & Percentage >= 5) # need to filter, direct output BMDExpress

LU_norm_modules = fread(file.path(inputDir, "Leiden", paste0(studyNR, "_log2cpm_functionalClas_output.txt")), check.names = TRUE) %>%
  filter(Genes.That.Passed.All.Filters >= 3 & Percentage >= 5) # need to filter, direct output BMDExpress

Sciensano_norm_HALLMARK = fread(file.path(inputDir, "Sciensano", "medianBMD_pathways_normalized_counts_finalfiltered.txt"), check.names = TRUE) %>%
  filter(!Pathway.Name %in% c("TGxDDI64", "GENOMARK84")) # filter for HALLMARK gene sets

Sciensano_norm_TXDDI_GENOMARK = fread(file.path(inputDir, "Sciensano", "medianBMD_pathways_normalized_counts_finalfiltered.txt"), check.names = TRUE) %>%
  filter(Pathway.Name %in% c("TGxDDI64", "GENOMARK84"),
         Genes.That.Passed.All.Filters >= 3) # filter for TGxDDI64 and GENOMARK84 biomarker sets

BPI_norm_HALLMARK = fread(file.path(inputDir, "BPI", "All_HALLOutV3.txt"), check.names = TRUE) 
  
# BPI_norm_KEGG = fread(file.path(inputDir, "BPI", "All_KEGGOutV3.txt"), check.names = TRUE) 

# BPI_norm_REACTOME = fread(file.path(inputDir, "BPI", "All_ReactOutV3.txt"), check.names = TRUE) 

BPI_norm_WIKIPATHWAYS = fread(file.path(inputDir, "BPI", "All_WPOutV3.txt"), check.names = TRUE) 



# pathway overview
AU_pathway_overview = fread(file.path(inputDir, "Aristotle", paste0(studyNR, "_PathwayIdentifiers.txt")), check.names = TRUE) %>% select(-"X")

GU_pathway_overview = fread(file.path(inputDir, "Ghent", "pathway_overview.txt"), sep = " ", check.names = TRUE)

LU_txgmapr_egs = fread(file.path(inputDir, "Leiden", paste0(studyNR, "_TXGMAPr_module_egs.txt")), check.names = TRUE)

LU_pathway_overview = fread(file.path(inputDir, "Leiden", paste0(studyNR, "_gene_module_overview.txt")), check.names = TRUE) 

Sciensano_pathway_overview = fread(file.path(inputDir, "Sciensano", "pathway_overview.txt"), check.names = TRUE)


#  load pathway-gene memberships gsea
gmt_file_hallmarks = file.path(here(), "input", "gsea_pathways", "hallmarks.v2023.2.Hs.symbols.gmt")
# gmt_file_kegg = file.path(here(), "input", "gsea_pathways", "c2.cp.kegg_legacy.v2024.1.Hs.symbols.gmt")
gmt_file_reactome = file.path(here(), "input", "gsea_pathways", "c2.cp.reactome.v2024.1.Hs.symbols.gmt")
gmt_file_wikipathways = file.path(here(), "input", "gsea_pathways", "c2.cp.wikipathways.v2024.1.Hs.symbols.gmt")


gsea_hallmark = read.GMT(gmt_file_hallmarks)
gsea_hallmark_df = map_df(gsea_hallmark, ~as.data.frame(.x)) %>% dplyr::rename("pathway" = id, "gene_symbol" = genes)

gsea_reactome = read.GMT(gmt_file_reactome)
gsea_reactome_df = map_df(gsea_reactome, ~as.data.frame(.x)) %>% dplyr::rename("pathway" = id, "gene_symbol" = genes) 

gsea_wikipathways = read.GMT(gmt_file_wikipathways)
gsea_wikipathways_df = map_df(gsea_wikipathways, ~as.data.frame(.x)) %>% dplyr::rename("pathway" = id, "gene_symbol" = genes)


# BMD on pathway scores

# module eigengene scores
LU_BMD_pathway = fread(file.path(inputDir, "Leiden", paste0(studyNR, "_module_egs_BMD_output.txt")), check.names = TRUE) %>%
    filter(Best.BMD >= 0.1*0.1 & Best.BMD <= 50,
         Best.BMD.BMDL < 20,
         Best.BMDU.BMD < 20,
         Best.RSquared >= 0.8) # need to filter because output directly from BMDExpress


# NES scores
Sciensano_BMD_pathway = fread(file.path(inputDir, "Sciensano", "BMD_output_NES_final.txt"), check.names = TRUE) %>% select(-1) %>%
  filter(Best.BMD <= 50,
         Best.BMD.BMDL <=20,
         Best.BMDU.BMDL <=20,
         Best.fitPValue >= 0.1) %>% # filter
  filter(!pathway %in% c("TGxDDI64", "GENOMARK84"))

```



# Wrangle data 

## BMD normalized counts
```{r}

# normalized counts
AU_norm_BMD_select = AU_norm_BMD %>% mutate(timepoint = factor(
  str_extract(Analysis, "\\d{1,2}h"),
  levels = c("4h", "8h", "16h", "24h", "48h", "72h")
),
partner = "AU") %>% dplyr::select(
  gene_symbol_entrez_id,
  timepoint,
  "finalBMD" = BMD.zSD,
  "finalBMDU" = BMD.zSD.upper,
  "finalBMDL" = BMD.zSD.lower,
  partner
)


GU_norm_BMD_select = GU_norm_BMD %>% mutate(timepoint = factor(
  paste0(timepoint, "h"),
  levels = c("4h", "8h", "16h", "24h", "48h", "72h")
), partner = "GU") %>% dplyr::select(
  gene_symbol_entrez_id,
  timepoint,
  "finalBMD" = BMD.zSD,
  "finalBMDU" = BMD.zSD.upper,
  "finalBMDL" = BMD.zSD.lower,
  partner
)



LU_norm_BMD_select = LU_norm_BMD %>% mutate(timepoint = factor(
  str_extract(Analysis, "\\d{1,2}h"), 
  levels = c("4h", "8h", "16h", "24h", "48h", "72h")
  ),
  partner = "LU") %>% dplyr::select(
    "gene_symbol_entrez_id" = Probe.ID, 
    timepoint, 
    "finalBMD" = Best.BMD,
    "finalBMDU" = Best.BMDU,
    "finalBMDL" = Best.BMDL,
    partner
  )
  
  

Sciensano_norm_BMD_select = Sciensano_norm_BMD %>% mutate(timepoint = factor(
  str_extract(Analysis, "\\d{1,2}h"), 
  levels = c("4h", "8h", "16h", "24h", "48h", "72h")
  ),
  partner = "SC") %>% dplyr::select(
    gene_symbol_entrez_id,
    timepoint, 
    "finalBMD" = Best.BMD,
    "finalBMDU" = Best.BMDU,
    "finalBMDL" = Best.BMDL,
    partner
  )



BPI_norm_BMD_select = BPI_norm_BMD %>% mutate(timepoint = factor(
  timepoint, levels = c("4h", "8h", "16h", "24h", "48h", "72h")),
  partner = "BPI"
) %>% dplyr::select(
  gene_symbol_entrez_id,
  timepoint,
  "finalBMD" = BMD.zSD,
  "finalBMDU" = BMD.zSD.upper,
  "finalBMDL" = BMD.zSD.lower,
  partner
)
  



# log2fc (need to adjust like above)
LU_fc_select = LU_fc_BMD %>% mutate(
  timepoint = factor(str_extract(Analysis, "\\d{1,2}h"), levels = c("4h", "8h", "16h", "24h", "48h", "72h")),
  partner = "LU"
) %>% dplyr::select(
  "gene_symbol_entrez_id" = Probe.ID, 
  timepoint,
  "finalBMD" = Best.BMD,
  "finalBMDU" = Best.BMDU,
  "finalBMDL" = Best.BMDL,
  partner
)


ODAF_fc_select = ODAF_fc_BMD %>% mutate(timepoint = factor(
  str_extract(Analysis, "\\d{1,2}h"), levels = c("4h", "8h", "16h", "24h", "48h", "72h")),
  partner = "R-ODAF"
  ) %>% dplyr::select(
    "gene_symbol_entrez_id" = Probe.ID,
    timepoint,
    "finalBMD" = Best.BMD,
    "finalBMDU" = Best.BMDU,
    "finalBMDL" = Best.BMDL,
    partner
  )
  
  
```


### BMD HALLMARK pathways
```{r}

# median BMD HALLMARK
AU_norm_HALLMARK_select = AU_norm_HALLMARK %>% mutate(
  timepoint = factor(str_extract(Analysis, "\\d{1,2}h"), levels = c("4h", "8h", "16h", "24h", "48h", "72h")),
  partner = "AU") %>% dplyr::select(
    "Pathway.Name" = Description,
    timepoint,
    "medianBMD" = Median,
    "medianBMDU" = Range_Max,
    "medianBMDL" = Range_Min,
    partner
  ) %>% unique() %>% drop_na()


GU_norm_HALLMARK_select = GU_norm_HALLMARK %>% mutate(
  timepoint = factor(timepoint, levels = c("4h", "8h", "16h", "24h", "48h", "72h")),
  partner = "GU") %>% dplyr::select(
    Pathway.Name,
    timepoint,
    "medianBMD" = BMD.median,
    "medianBMDU" = BMD.thirdquartile,
    "medianBMDL" = BMD.firstquartile,
    partner
  ) %>% unique() %>% drop_na()



LU_norm_HALLMARK_select = LU_norm_HALLMARK %>% mutate(
  timepoint = factor(str_extract(Analysis, "\\d{1,2}h"), levels = c("4h", "8h", "16h", "24h", "48h", "72h")),
  partner = "LU"
) %>% dplyr::select(
  "Pathway.Name" = GO.Pathway.Gene.Set.Gene.Name, 
  timepoint,
  "medianBMD" = BMD.Median,
  "medianBMDU" = BMDU.Median,
  "medianBMDL" = BMDL.Median,
  partner
) %>% unique() %>% drop_na()




Sciensano_norm_HALLMARK_select = Sciensano_norm_HALLMARK %>% mutate(timepoint = factor(
  str_extract(Analysis, "\\d{1,2}h"),
  levels = c("4h", "8h", "16h", "24h", "48h", "72h")
), partner = "SC") %>%
  dplyr::select(
    Pathway.Name,
    timepoint,
    "medianBMD" = Median,
    "medianBMDU" = BMDU.Median,
    "medianBMDL" = BMDL.Median,
    partner
  ) %>% unique() %>% drop_na()



BPI_norm_HALLMARK_select = BPI_norm_HALLMARK %>% mutate(
  timepoint = factor(Timepoint, levels = c("4h", "8h", "16h", "24h", "48h", "72h")),
  partner = "BPI"
) %>% dplyr::select(
  "Pathway.Name" = Description,
  timepoint,
  "medianBMD" = MedianBMD,
  "medianBMDU" = MedianBMDU,
  "medianBMDL" = MedianBMDL,
  partner
) %>% unique() %>% drop_na()


```



## BMD pathways of choice
```{r}

# median BMD pathways of choice
AU_norm_KEGG_select = AU_norm_KEGG %>% mutate(
  timepoint = factor(str_extract(Analysis, "\\d{1,2}h"), levels = c("4h", "8h", "16h", "24h", "48h", "72h")),
  partner = "AU") %>% dplyr::select(
    "Pathway.Name" = Description,
    timepoint,
    "medianBMD" = Median,
    "medianBMDU" = Range_Max,
    "medianBMDL" = Range_Min,
    partner
  ) %>% unique() %>% drop_na()




LU_norm_modules_select = LU_norm_modules %>% mutate(
  timepoint = factor(str_extract(Analysis, "\\d{1,2}h"), levels = c("4h", "8h", "16h", "24h", "48h", "72h")),
  partner = "LU"
) %>% dplyr::select(
  "Pathway.Name" = GO.Pathway.Gene.Set.Gene.Name, 
  timepoint,
  "medianBMD" = BMD.Median,
  "medianBMDU" = BMDU.Median,
  "medianBMDL" = BMDL.Median,
  partner
) %>% unique() %>% drop_na()



Sciensano_norm_TXDDI_GENOMARK_select = Sciensano_norm_TXDDI_GENOMARK %>% mutate(timepoint = factor(
  str_extract(Analysis, "\\d{1,2}h"),
  levels = c("4h", "8h", "16h", "24h", "48h", "72h")
), partner = "SC") %>%
  dplyr::select(
    Pathway.Name,
    timepoint,
    "medianBMD" = Median,
    "medianBMDU" = BMDU.Median,
    "medianBMDL" = BMDL.Median,
    partner
  ) %>% unique() %>% drop_na()


BPI_norm_WIKIPATHWAYS_select = BPI_norm_WIKIPATHWAYS %>% mutate(
  timepoint = factor(Timepoint, levels = c("4h", "8h", "16h", "24h", "48h", "72h")),
  partner = "BPI"
) %>% dplyr::select(
  "Pathway.Name" = Description,
  timepoint,
  "medianBMD" = MedianBMD,
  "medianBMDU" = MedianBMDU,
  "medianBMDL" = MedianBMDL,
  partner
) %>% unique() %>% drop_na()



# BPI_norm_REACTOME_select = BPI_norm_REACTOME %>% mutate(
#   timepoint = factor(paste0(Timepoint, "r"), levels = c("4hr", "8hr", "16hr", "24hr", "48hr", "72hr")),
#   partner = "BPI"
# ) %>% dplyr::select(
#   "Pathway.Name" = Description,
#   timepoint,
#   "medianBMD" = MedianBMD,
#   "medianBMDU" = MedianBMDU,
#   "medianBMDL" = MedianBMDL,
#   partner
# ) %>% unique() %>% drop_na()



# BPI_norm_KEGG_select = BPI_norm_WIKIPATHWAYS %>% mutate(
#   timepoint = factor(paste0(Timepoint, "r"), levels = c("4hr", "8hr", "16hr", "24hr", "48hr", "72hr")),
#   partner = "BPI"
# ) %>% dplyr::select(
#   "Pathway.Name" = Description,
#   timepoint,
#   "medianBMD" = MedianBMD,
#   "medianBMDU" = MedianBMDU,
#   "medianBMDL" = MedianBMDL,
#   partner
# ) %>% unique() %>% drop_na()





```





## BMD from pathway scores
```{r}
# module eigengene scores
LU_BMD_pathway_select = LU_BMD_pathway %>%
  mutate(timepoint = factor(str_extract(Analysis, "\\d{1,2}h"), levels = c("4h", "8h", "16h", "24h", "48h", "72h"))) %>%
  dplyr::rename("finalBMD" = Best.BMD,
                "finalBMDU" = Best.BMDU,
                "finalBMDL" = Best.BMDL,
                "pathway" = Probe.ID)


# NES scores
Sciensano_BMD_pathway_select = Sciensano_BMD_pathway %>%
  mutate(timepoint = factor(str_extract(Analysis, "\\d{1,2}h"), levels = c("4h", "8h", "16h", "24h", "48h", "72h"))) %>%
  dplyr::rename("finalBMD" = Best.BMD,
                "finalBMDU" = Best.BMDU,
                "finalBMDL" = Best.BMDL) 

```



## Pathway overview
```{r}
LU_pathway_overview_select = LU_pathway_overview %>% select(gene_symbol, entrez_id, module) %>%
  mutate(gene_symbol = gsub("id_", "", gene_symbol),
         entrez_id = gsub("id_", "", entrez_id)) %>%
  unite(gene_symbol, entrez_id, col = "gene_symbol_entrez_id") %>%
  unique()
```


## Generate needed combined data
```{r}
# normalized counts BMD combined
df_list = list(AU_norm_BMD_select, GU_norm_BMD_select, LU_norm_BMD_select, Sciensano_norm_BMD_select, BPI_norm_BMD_select)

norm_BMD_combined = bind_rows(df_list) %>% as_tibble()

# make wide
gene_BMD_list = list(
  AU_norm_BMD_select %>% select(gene_symbol_entrez_id, "AU_finalBMD" = finalBMD, timepoint),
  GU_norm_BMD_select %>% select(gene_symbol_entrez_id, "GU_finalBMD" = finalBMD, timepoint),
  LU_norm_BMD_select %>% select(gene_symbol_entrez_id, "LU_finalBMD" = finalBMD, timepoint),
  Sciensano_norm_BMD_select %>% select(gene_symbol_entrez_id, "SC_finalBMD" = finalBMD, timepoint),
  BPI_norm_BMD_select %>% select(gene_symbol_entrez_id, "BPI_finalBMD" = finalBMD, timepoint)
  )

norm_BMD_combined_wide = gene_BMD_list %>% reduce(full_join, by = c("gene_symbol_entrez_id", "timepoint"))


# log2fc BMD combined
df_list = list(LU_fc_select, ODAF_fc_select)

fc_BMD_combined = bind_rows(df_list) %>% as_tibble()



# HALLMARK pathway combined
df_list_HALLMARK = list(AU_norm_HALLMARK_select, GU_norm_HALLMARK_select, LU_norm_HALLMARK_select, Sciensano_norm_HALLMARK_select, BPI_norm_HALLMARK_select)

norm_HALLMARK_combined = bind_rows(df_list_HALLMARK) %>% as_tibble()


# make wide df
df_list_HALLMARK = list(AU_norm_HALLMARK_select %>% select(Pathway.Name, timepoint, "AU_medianBMD" = medianBMD),
                        GU_norm_HALLMARK_select %>% select(Pathway.Name, timepoint, "GU_medianBMD" = medianBMD),
                        LU_norm_HALLMARK_select %>% select(Pathway.Name, timepoint, "LU_medianBMD" = medianBMD),
                        Sciensano_norm_HALLMARK_select %>% select(Pathway.Name, timepoint, "SC_medianBMD" = medianBMD),
                        BPI_norm_HALLMARK_select %>% select(Pathway.Name, timepoint, "BPI_medianBMD" = medianBMD))

norm_HALLMARK_combined_wide = df_list_HALLMARK %>% reduce(full_join, by = c("Pathway.Name", "timepoint"))



# Pathway of choice combined
df_list_pathwaysChoice = list(AU_norm_KEGG_select, GU_norm_HALLMARK_select, LU_norm_modules_select, Sciensano_norm_TXDDI_GENOMARK_select, BPI_norm_WIKIPATHWAYS)

norm_pathwaysChoice_combined = bind_rows(df_list_pathwaysChoice) %>% as_tibble()




# HALLMARK P53 genes BMD combined
genes_in_HALLMARKp53 = gsea_hallmark_df %>% filter(pathway == "HALLMARK_P53_PATHWAY") %>% pull(gene_symbol) %>% unique()
norm_BMD_combined_HALLMARKp53 = norm_BMD_combined %>% separate(gene_symbol_entrez_id, into = c("gene_symbol", "entrez_id"), sep = "_") %>% filter(gene_symbol %in% genes_in_HALLMARKp53)






```



# Save data
```{r}
save(
  # BMD normalized counts
  AU_norm_BMD_select,
  BPI_norm_BMD_select,
  GU_norm_BMD_select,
  LU_norm_BMD_select,
  Sciensano_norm_BMD_select,
  
  norm_BMD_combined,
  norm_BMD_combined_wide,
  
  # BMD HALLMARK pathways
  AU_norm_HALLMARK_select,
  BPI_norm_HALLMARK_select,
  GU_norm_HALLMARK_select,
  LU_norm_HALLMARK_select,
  Sciensano_norm_HALLMARK_select,
  
  norm_BMD_combined_HALLMARKp53,
  norm_HALLMARK_combined,
  norm_HALLMARK_combined_wide,
  
  # BMD pathways of choice
  AU_norm_KEGG_select,
  BPI_norm_WIKIPATHWAYS_select,
  LU_norm_modules_select,
  Sciensano_norm_TXDDI_GENOMARK_select,
  
  norm_pathwaysChoice_combined,
  
  # pathway overview
  AU_pathway_overview, 
  GU_pathway_overview,
  LU_pathway_overview_select,
  Sciensano_pathway_overview,
  
  gsea_hallmark_df,
  # gsea_reactome_df, 
  gsea_wikipathways_df, # no list from BPI, so copied from gsea
  
  
  # BMD on pathway scores
  LU_BMD_pathway_select,
  Sciensano_BMD_pathway_select,
  
  # save
  file = file.path(outputDir, "WrangledInput", "WrangledInputData.Rdata")
)
```

